### ISSUE TITLE
Single/Class Table Inheritance

### ISSUE THREAD

**Issue by marcguyer** [webimpress/doctrine-zend-hydrator#2]
I see that no attention is given to inheritance `discriminatorColumn`, only the base metadata is used for hydration/extraction. Is this intentional?

**Comment by michalbundyra** [comment]
@marcguyer The library has been moved to doctrine org - see: [`doctrine/doctrine-zend-hydrator`](https://github.com/doctrine/doctrine-zend-hydrator). Please open the issue there, if it still relevant. I can't move it, unfortunately. Sorry for the inconvenience.
